### ISSUE TITLE
MySQLService的StaticPage类有问题

### ISSUE THREAD

**Issue by Craft24** [CactusCms/Cactus#1]
[MySQLService的StaticPage类有问题](https://github.com/CactusCms/Cactus/blob/master/Cactus.MySQLService/CMS/StaticPageService.cs)  
`using (IDbConnection conn = SqlString.GetSQLiteConnection())`  
应该改为  
`using (IDbConnection conn = SqlString.GetMySqlConnection())`

**Comment by liuww111** [comment]
已在修改，感谢
